# ============================================
# Stage 1: Dependencies
# ============================================
FROM node:22-alpine AS deps

WORKDIR /app

# Copy package files
COPY package.json package-lock.json ./

# Install all dependencies (including devDependencies for build)
RUN npm ci

# ============================================
# Stage 2: Builder
# ============================================
FROM node:22-alpine AS builder

WORKDIR /app

# Copy dependencies from deps stage
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Build-time arguments for PUBLIC_* variables (baked into bundle via $env/static/public)
ARG PUBLIC_CDN_URL
ARG PUBLIC_TAWK_PROPERTY_ID
ARG PUBLIC_TAWK_WIDGET_ID
ARG PUBLIC_SCHEDULE_CALL_ENABLED=false
ARG PUBLIC_INSIGHTS_ENABLED=false

# PUBLIC_BUSINESS_* variables
ARG PUBLIC_BUSINESS_NAME
ARG PUBLIC_BUSINESS_ALT_NAME
ARG PUBLIC_BUSINESS_URL
ARG PUBLIC_BUSINESS_DESCRIPTION
ARG PUBLIC_BUSINESS_PHONE
ARG PUBLIC_BUSINESS_EMAIL
ARG PUBLIC_BUSINESS_PRICE_RANGE
ARG PUBLIC_BUSINESS_STREET
ARG PUBLIC_BUSINESS_CITY
ARG PUBLIC_BUSINESS_STATE
ARG PUBLIC_BUSINESS_ZIP
ARG PUBLIC_BUSINESS_COUNTRY
ARG PUBLIC_BUSINESS_LATITUDE
ARG PUBLIC_BUSINESS_LONGITUDE
ARG PUBLIC_FOUNDER_NAME
ARG PUBLIC_FOUNDER_TITLE
ARG PUBLIC_BUSINESS_AREA_SERVED
ARG PUBLIC_BUSINESS_HOURS_DAYS
ARG PUBLIC_BUSINESS_HOURS_OPEN
ARG PUBLIC_BUSINESS_HOURS_CLOSE

# Private build-time variables ($env/static/private)
ARG WEBHOOK_JWT_SECRET
ARG N8N_CONTACT_WEBHOOK_URL
ARG N8N_HEALTH_CHECK_WEBHOOK_URL
ARG RATE_LIMIT_WINDOW=60000
ARG RATE_LIMIT_MAX_REQUESTS=10

# Google API (used in vite.config.js define)
ARG GOOGLE_PLACES_API_KEY
ARG GOOGLE_BUSINESS_PLACE_ID

# Card configuration variables
ARG CARD_JAMAAL_NAME
ARG CARD_JAMAAL_PERSON
ARG CARD_JAMAAL_TITLE
ARG CARD_JAMAAL_PHONE
ARG CARD_JAMAAL_EMAIL
ARG CARD_JAMAAL_STREET
ARG CARD_JAMAAL_CITY
ARG CARD_JAMAAL_STATE
ARG CARD_JAMAAL_ZIP
ARG CARD_JAMAAL_COUNTRY
ARG CARD_JAMAAL_IMAGE

# Convert ARGs to ENVs for build process
ENV PUBLIC_CDN_URL=$PUBLIC_CDN_URL \
    PUBLIC_TAWK_PROPERTY_ID=$PUBLIC_TAWK_PROPERTY_ID \
    PUBLIC_TAWK_WIDGET_ID=$PUBLIC_TAWK_WIDGET_ID \
    PUBLIC_SCHEDULE_CALL_ENABLED=$PUBLIC_SCHEDULE_CALL_ENABLED \
    PUBLIC_INSIGHTS_ENABLED=$PUBLIC_INSIGHTS_ENABLED \
    PUBLIC_BUSINESS_NAME=$PUBLIC_BUSINESS_NAME \
    PUBLIC_BUSINESS_ALT_NAME=$PUBLIC_BUSINESS_ALT_NAME \
    PUBLIC_BUSINESS_URL=$PUBLIC_BUSINESS_URL \
    PUBLIC_BUSINESS_DESCRIPTION=$PUBLIC_BUSINESS_DESCRIPTION \
    PUBLIC_BUSINESS_PHONE=$PUBLIC_BUSINESS_PHONE \
    PUBLIC_BUSINESS_EMAIL=$PUBLIC_BUSINESS_EMAIL \
    PUBLIC_BUSINESS_PRICE_RANGE=$PUBLIC_BUSINESS_PRICE_RANGE \
    PUBLIC_BUSINESS_STREET=$PUBLIC_BUSINESS_STREET \
    PUBLIC_BUSINESS_CITY=$PUBLIC_BUSINESS_CITY \
    PUBLIC_BUSINESS_STATE=$PUBLIC_BUSINESS_STATE \
    PUBLIC_BUSINESS_ZIP=$PUBLIC_BUSINESS_ZIP \
    PUBLIC_BUSINESS_COUNTRY=$PUBLIC_BUSINESS_COUNTRY \
    PUBLIC_BUSINESS_LATITUDE=$PUBLIC_BUSINESS_LATITUDE \
    PUBLIC_BUSINESS_LONGITUDE=$PUBLIC_BUSINESS_LONGITUDE \
    PUBLIC_FOUNDER_NAME=$PUBLIC_FOUNDER_NAME \
    PUBLIC_FOUNDER_TITLE=$PUBLIC_FOUNDER_TITLE \
    PUBLIC_BUSINESS_AREA_SERVED=$PUBLIC_BUSINESS_AREA_SERVED \
    PUBLIC_BUSINESS_HOURS_DAYS=$PUBLIC_BUSINESS_HOURS_DAYS \
    PUBLIC_BUSINESS_HOURS_OPEN=$PUBLIC_BUSINESS_HOURS_OPEN \
    PUBLIC_BUSINESS_HOURS_CLOSE=$PUBLIC_BUSINESS_HOURS_CLOSE \
    WEBHOOK_JWT_SECRET=$WEBHOOK_JWT_SECRET \
    N8N_CONTACT_WEBHOOK_URL=$N8N_CONTACT_WEBHOOK_URL \
    N8N_HEALTH_CHECK_WEBHOOK_URL=$N8N_HEALTH_CHECK_WEBHOOK_URL \
    RATE_LIMIT_WINDOW=$RATE_LIMIT_WINDOW \
    RATE_LIMIT_MAX_REQUESTS=$RATE_LIMIT_MAX_REQUESTS \
    GOOGLE_PLACES_API_KEY=$GOOGLE_PLACES_API_KEY \
    GOOGLE_BUSINESS_PLACE_ID=$GOOGLE_BUSINESS_PLACE_ID \
    CARD_JAMAAL_NAME=$CARD_JAMAAL_NAME \
    CARD_JAMAAL_PERSON=$CARD_JAMAAL_PERSON \
    CARD_JAMAAL_TITLE=$CARD_JAMAAL_TITLE \
    CARD_JAMAAL_PHONE=$CARD_JAMAAL_PHONE \
    CARD_JAMAAL_EMAIL=$CARD_JAMAAL_EMAIL \
    CARD_JAMAAL_STREET=$CARD_JAMAAL_STREET \
    CARD_JAMAAL_CITY=$CARD_JAMAAL_CITY \
    CARD_JAMAAL_STATE=$CARD_JAMAAL_STATE \
    CARD_JAMAAL_ZIP=$CARD_JAMAAL_ZIP \
    CARD_JAMAAL_COUNTRY=$CARD_JAMAAL_COUNTRY \
    CARD_JAMAAL_IMAGE=$CARD_JAMAAL_IMAGE

# Build the application
RUN npm run build

# ============================================
# Stage 3: Production Runner
# ============================================
FROM node:22-alpine AS runner

WORKDIR /app

# Create non-root user for security
RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 sveltekit

# Copy package files and install production dependencies only
COPY package.json package-lock.json ./
RUN npm ci --omit=dev && npm cache clean --force

# Copy built application from builder stage
COPY --from=builder /app/build ./build

# Set ownership
RUN chown -R sveltekit:nodejs /app

# Switch to non-root user
USER sveltekit

# Runtime environment variables
ENV NODE_ENV=production \
    PORT=3000 \
    HOST=0.0.0.0

# Expose the port
EXPOSE 3000

# Health check
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
    CMD wget --no-verbose --tries=1 --spider http://localhost:3000/ || exit 1

# Start the application
CMD ["node", "build/index.js"]
