name: Build and Deploy to Server

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@main

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '21'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Add server to known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}


    - name: Upload .env file
      run: |
        echo "PUBLIC_CDN_URL=${{ secrets.PUBLIC_CDN_URL }}" > .env
        scp .env ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }}:${{ secrets.SERVER_DIRECTORY }}/.env

    - name: Build project
      run: npm run build

    - name: Upload build and dependencies
      run: |
        ls -la build/
        scp -r build ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }}:${{ secrets.SERVER_DIRECTORY }}/
        scp package.json package-lock.json ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }}:${{ secrets.SERVER_DIRECTORY }}/

    - name: SSH and run post-deploy commands
      run: |
        ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }} << 'EOF'
        set -e

        cd ${{ secrets.SERVER_DIRECTORY }}

        echo "Cleaning up old node_modules..."
        rm -rf node_modules

        echo "Installing production dependencies..."
        npm ci --omit=dev

        echo "Restarting app with PM2..."
        pm2 delete j2it.us || true
        PORT=${{ secrets.APP_PORT }} pm2 start build/index.js --name j2it.us
        pm2 save
        EOF